
    alias bat='upower -i /org/freedesktop/UPower/devices/battery_BAT0'
    alias snd='alsamixer'
    alias net='nmcli'
    alias nm='nmtui'
    alias vol='pactl -- set-sink-volume 0'
    alias brg='~/.config/awesome/brightness-xrandr.sh'
    alias winshow='VBoxSDL --startvm Windows --separate'
    alias winexec='VBoxManage startvm Windows --type headless'
    alias gcintel='/usr/local/bin/usman-graphics/intel.sh'
    alias gcnvidia='/usr/local/bin/usman-graphics/nvidia.sh'
    alias kaliexec='VBoxManage startvm Kali --type headless'
    alias kalishow='VBoxSDL --startvm Kali --separate'
    alias kalikill='VBoxManage controlvm Kali poweroff'
    alias kalissh='ssh ace@192.168.56.5'
    alias storage='cd /media/storage'
    alias citra='flatpak run org.citra.citra-canary'
